/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/ui/Alert.vue')['default']
    CategoryForm: typeof import('./components/CategoryForm.vue')['default']
    Dialog: typeof import('./components/ui/Dialog.vue')['default']
    Loading: typeof import('./components/ui/Loading.vue')['default']
    Message: typeof import('./components/ui/Message.vue')['default']
    ProductForm: typeof import('./components/ProductForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./components/UserForm.vue')['default']
  }
}
