server.port=5000
jwt.secret=hT9bFv2Yx4Wz71MkU3aLr5EqNcJ6BgQ8

spring.datasource.url=jdbc:postgresql://cake-shop-project.cxquwkqyo34y.ap-southeast-2.rds.amazonaws.com:5432/cake-shop-project
spring.datasource.username=postgres
spring.datasource.password=xji6cl4p953
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=admin
spring.security.user.password=123456